# Generated by Django 5.1.6 on 2025-03-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10101, max_digits=10),
            preserve_default=False,
        ),
    ]
