# Generated by Django 5.1.6 on 2025-03-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='announcement',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
