# Generated by Django 5.1.6 on 2025-03-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_city_announcement_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
